if (${CANGJIE_TARGET_OS} STREQUAL "windows" AND ${CANGJIE_TARGET_ENV} STREQUAL "gnu")
    add_compile_definitions(_POSIX_C_SOURCE=200112L)
endif()
SET(BAIZE_XML_SRC ${CMAKE_SOURCE_DIR}/third_party/baize/xml)
include_directories(${BAIZE_XML_SRC}/include)
FILE(GLOB XML_FFI_SRC ./xml_native.c ${BAIZE_XML_SRC}/src/*.c)
set(libname xmlFFI)
add_library(${libname}-objs OBJECT ${XML_FFI_SRC})
target_compile_options(${libname}-objs PRIVATE ${CMAKE_C_COVERAGE_FLAGS})
add_library(${libname} STATIC $<TARGET_OBJECTS:xmlFFI-objs>)
install_cangjie_library_ffi(${libname})
